name: Parallel Jobs with Sleep

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: self-hosted

    steps:
      - name: Parallel Job 1
        run: |
          echo "Starting Parallel Job 1"
          sleep 30  # Sleep for 30 seconds
          echo "Parallel Job 1 Completed"

  job2:
    runs-on: self-hosted

    steps:
      - name: Parallel Job 2
        run: |
          echo "Starting Parallel Job 2"
          sleep 45  # Sleep for 45 seconds
          echo "Parallel Job 2 Completed"
